<a href="https://colab.research.google.com/github/aabioumaima/Accuracy-Precision-Recall-and-F1-Score/blob/main/PyTorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* PyTorch Basic : 

In [ ]:
import torch
import torch.nn as nn

#basic autograd example1:
x = torch.tensor(1., requires_grad = True)
w = torch.tensor(2., requires_grad = True)
b = torch.tensor(3., requires_grad = True)

y = w * x + b # y = 2 * x + 3

#Compute gradients.
y.backward()

print('dy/dx', x.grad) #x.grad = 2
print('dy/dw', w.grad) #w.grad = 1
print('dy/db', b.grad) #b.grad = 1

dy/dx tensor(2.)
dy/dw tensor(1.)
dy/db tensor(1.)


In [ ]:
#basic autograd example2:

#Create tensors of shape (10, 3) and (10, 2)
x = torch.randn(10, 3)
y = torch.randn(10, 2)

#Building a fully connected layer (FCL)
linear = nn.Linear(3, 2)
print('w: ', linear.weight)
print('b: ', linear.bias)

#Build loss function and optimizer
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr = 0.01)

#Forward pass.
pred = linear(x)

#Compute loss.
loss = criterion(pred, y)
print('loss: ', loss.item())

#Backward pass.
loss.backward()

#Print out the gradients.
print('dL/dw: ', linear.weight.grad)
print('dL/db: ', linear.bias.grad)

#1-step gradient descent.
optimizer.step()

#Print out the loss after 1-step gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

w:  Parameter containing:
tensor([[ 0.1128, -0.2006, -0.1201],
        [ 0.4623,  0.4148,  0.3334]], requires_grad=True)
b:  Parameter containing:
tensor([-0.2395,  0.5171], requires_grad=True)
loss:  1.2087687253952026
dL/dw:  tensor([[-0.3132, -0.0970, -0.1137],
        [ 1.0768,  0.4647,  0.4242]])
dL/db:  tensor([-0.2912,  0.7350])
loss after 1 step optimization:  1.1859595775604248


* Linear Regression: 

In [ ]:
import numpy as np
import torch

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype = 'float32')

In [ ]:
# Targets (apples, orange)
targets = np.array([[56, 70],
                   [81, 101],
                   [119, 133],
                   [22, 37],
                   [103, 119]], dtype = 'float32')

In [ ]:
#Converted to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


* Linear regression model from scratch:

In [ ]:
#Weights and biases
w = torch.randn(2, 3, requires_grad = True) #2 rows and 3 columns
b = torch.randn(2, requires_grad = True) #2rows only
print(w)
print(b)

tensor([[-0.2985, -0.0514,  0.6771],
        [-0.9323, -0.8078,  0.1610]], requires_grad=True)
tensor([ 0.3345, -0.3533], requires_grad=True)


In [ ]:
def model(x):
  return x @ w.t() + b 

In [ ]:
#Generate predictions
preds = model(inputs)
print(preds)

tensor([[   4.2188, -115.6115],
        [  11.9865, -145.9757],
        [   6.7529, -180.3719],
        [  -7.2653, -124.2270],
        [  22.2039, -130.9613]], grad_fn=<AddBackward0>)


In [ ]:
#Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


* Loss function :

In [ ]:
#MSE loss
def mse(t1, t2):
  diff = t1 - t2
  return torch.sum(diff * diff) /diff.numel()

In [ ]:
#Compute loss
loss = mse(preds, targets)
print(loss)

tensor(30955.3438, grad_fn=<DivBackward0>)


* Compute gradients:

In [ ]:
#Compute gradients
loss.backward()

In [ ]:
#Gradients fro weights
print(w)
print(w.grad)


tensor([[-0.2985, -0.0514,  0.6771],
        [-0.9323, -0.8078,  0.1610]], requires_grad=True)
tensor([[ -5677.1484,  -6719.6934,  -3978.4656],
        [-19396.0547, -21418.1426, -13085.2012]])


In [ ]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
#1e-5: learning rate

In [ ]:
# Let's verify that the loss is actually lower
loss = mse(preds, targets)
print(loss)

tensor(30955.3438, grad_fn=<DivBackward0>)


In [ ]:
#initialize the weitghts with zero
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


* Train the model using gradient descent

In [ ]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[  14.5768,  -81.4733],
        [  25.6129, -101.1005],
        [  23.0046, -127.2053],
        [   2.8875,  -90.3894],
        [  35.3577,  -87.8547]], grad_fn=<AddBackward0>)


In [ ]:
#Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(20945.1973, grad_fn=<DivBackward0>)


In [ ]:
#Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ -4606.5015,  -5565.6592,  -3267.1653],
        [-15870.6494, -17627.3691, -10746.5850]])
tensor([ -55.9121, -189.6046])


In [ ]:
#Adjusting the weights by substracting a samll quantity to the gradients
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
#Reset the gradient to zero
  w = w.grad.zero_()
  b = b.grad.zero_()

In [ ]:
print(w)
print(b)

#Caculate the loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])
tensor(8327.0996)


* Train for multiple epochs

In [ ]:
# Train for 100 epochs
w = torch.randn(2, 3, requires_grad = True) #2 rows and 3 columns
b = torch.randn(2, requires_grad = True) #2rows only
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [ ]:
#Let's verify that the loss is lower
#Calculate the loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(1022.5233, grad_fn=<DivBackward0>)


In [ ]:
#Predictions
preds

tensor([[ 59.3974,  83.7729],
        [ 95.2506, 101.3531],
        [ 85.4385, 109.7617],
        [ 35.3429, 113.9009],
        [116.2644,  75.5640]], grad_fn=<AddBackward0>)

In [ ]:
#Targets 
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

* Linear regression using PyTorch built-ins

In [ ]:
import torch.nn as nn

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

* Dataset and DataLoader

In [ ]:
from torch.utils.data import TensorDataset

In [ ]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [ ]:
from torch.utils.data import DataLoader

In [ ]:
# Define data loader 
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle = True)

In [ ]:
for xb, yb  in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 87., 135.,  57.],
        [ 74.,  66.,  43.],
        [ 73.,  66.,  44.],
        [ 91.,  87.,  65.],
        [ 91.,  88.,  64.]])
tensor([[118., 134.],
        [ 57.,  69.],
        [ 57.,  69.],
        [ 80., 102.],
        [ 81., 101.]])


* nn.Linear

In [ ]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.1407,  0.3991, -0.4392],
        [-0.0179, -0.3114, -0.1745]], requires_grad=True)
Parameter containing:
tensor([-0.3619, -0.5158], requires_grad=True)


In [ ]:
#Parameters (2eme methode)
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1407,  0.3991, -0.4392],
         [-0.0179, -0.3114, -0.1745]], requires_grad=True),
 Parameter containing:
 tensor([-0.3619, -0.5158], requires_grad=True)]

In [ ]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 17.7659, -30.1924],
        [ 19.4571, -40.7193],
        [ 39.8897, -53.9249],
        [ 14.9022, -22.1918],
        [ 16.9195, -43.8630],
        [ 17.5074, -29.8990],
        [ 18.6188, -40.5824],
        [ 39.5912, -54.1174],
        [ 15.1607, -22.4853],
        [ 16.3396, -44.0196],
        [ 16.9275, -30.0556],
        [ 19.1987, -40.4258],
        [ 40.7280, -54.0618],
        [ 15.4822, -22.0352],
        [ 17.1779, -44.1565]], grad_fn=<AddmmBackward0>)

* Loss Function :

In [ ]:
import torch.nn.functional as F

In [ ]:
# Define loss function
loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(11403.2998, grad_fn=<MseLossBackward0>)


* Optimizer :

In [ ]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)

* Train the model :

In [ ]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [ ]:
#Let's train the model for 100 epochs.

fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 533.6547
Epoch [20/100], Loss: 709.9498
Epoch [30/100], Loss: 216.6245
Epoch [40/100], Loss: 105.4170
Epoch [50/100], Loss: 126.6201
Epoch [60/100], Loss: 62.1300
Epoch [70/100], Loss: 49.1495
Epoch [80/100], Loss: 78.6843
Epoch [90/100], Loss: 56.2037
Epoch [100/100], Loss: 47.5937


In [ ]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.3318,  71.8020],
        [ 77.7300,  98.3056],
        [125.7615, 135.7279],
        [ 28.6653,  46.0151],
        [ 89.7247, 109.6862],
        [ 57.1365,  70.8586],
        [ 76.7245,  97.8992],
        [125.6283, 136.1121],
        [ 29.8607,  46.9584],
        [ 89.9146, 110.2232],
        [ 57.3264,  71.3956],
        [ 76.5346,  97.3622],
        [126.7669, 136.1342],
        [ 28.4754,  45.4780],
        [ 90.9200, 110.6296]], grad_fn=<AddmmBackward0>)

In [ ]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [ ]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[53.9019, 68.6419]], grad_fn=<AddmmBackward0>)

In [ ]:
x = torch.randn(10, 3)
y = torch.randn(10, 2)

#Build a fullu connected layer
model = nn.Linear(3, 2)

#Weights and biases
list(model.parameters())

In [ ]:
#Generate predictions 
preds = model(x)
preds

In [ ]:
#Loss function
loss_fn = F.mse_loss
loss = loss_fn(preds, y)
print(loss)

In [ ]:
# Compute the gradient
loss.backward()

In [ ]:
#Optimizer
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [ ]:
#Update the parameters using gradient
opt.step()

In [ ]:
  #Reset the gradients to zero
opt.zero_grad()